In [22]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LinearRegression

In [7]:
df = pd.read_csv('Personal_Finance_Dataset.csv')
df

,Date,Transaction Description,Category,Amount,Type
0,2020-01-02,Score each.,Food & Drink,1485.69,Expense
1,2020-01-02,Quality throughout.,Utilities,1475.58,Expense
2,2020-01-04,Instead ahead despite measure ago.,Rent,1185.08,Expense
3,2020-01-05,Information last everything thank serve.,Investment,2291.00,Income
4,2020-01-13,Future choice whatever from.,Food & Drink,1126.88,Expense
...,...,...,...,...,...
1495,2024-12-28,Quite as when.,Rent,514.09,Expense
1496,2024-12-28,Right analysis mention.,Entertainment,727.25,Expense
1497,2024-12-28,No couple debate must.,Investment,1425.00,Income
1498,2024-12-29,Discussion black follow.,Shopping,655.78,Expense
1499,2024-12-29,Pressure activity defense detail.,Other,1480.00,Income

In [10]:
df = df.drop(columns = ['Date'])
df

,Transaction Description,Category,Amount,Type
0,Score each.,Food & Drink,1485.69,Expense
1,Quality throughout.,Utilities,1475.58,Expense
2,Instead ahead despite measure ago.,Rent,1185.08,Expense
3,Information last everything thank serve.,Investment,2291.00,Income
4,Future choice whatever from.,Food & Drink,1126.88,Expense
...,...,...,...,...
1495,Quite as when.,Rent,514.09,Expense
1496,Right analysis mention.,Entertainment,727.25,Expense
1497,No couple debate must.,Investment,1425.00,Income
1498,Discussion black follow.,Shopping,655.78,Expense
1499,Pressure activity defense detail.,Other,1480.00,Income

In [12]:
label_encoders = {}
for col in df.select_dtypes(include = 'object').columns:
    if col!= 'Type':
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])
        label_encoders[col]=le

In [14]:
target_encoder = LabelEncoder()
df['Type'] = target_encoder.fit_transform(df['Type'])

In [16]:
X = df.drop('Type', axis = 1)

In [18]:
y = df['Type']

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

In [48]:
model =LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [50]:
y_pred = model.predict(X_test)

In [51]:
accuracy = accuracy_score(y_pred, y_test)

In [52]:
accuracy

0.93